-- phpMyAdmin SQL Dump
-- version 4.8.4
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: Oct 19, 2020 at 02:28 PM
-- Server version: 5.7.24
-- PHP Version: 7.2.14

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `blog`
--
CREATE DATABASE IF NOT EXISTS `blog` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
USE `blog`;

-- --------------------------------------------------------

--
-- Table structure for table `posts`
--

DROP TABLE IF EXISTS `posts`;
CREATE TABLE IF NOT EXISTS `posts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(200) NOT NULL,
  `featured_img` varchar(100) NOT NULL,
  `description` varchar(10000) NOT NULL,
  `published` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `author` varchar(50) NOT NULL,
  `post_img` varchar(100) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=13 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `posts`
--

INSERT INTO `posts` (`id`, `title`, `featured_img`, `description`, `published`, `author`, `post_img`) VALUES
(7, 'Twitter Account of PM Modi\'s Website Was Hacked to Clear Paytm Hack Allegations: Report', 'bp7.webp', 'PM Narendra Modi’s website’s Twitter account was hacked in the early hours of Thursday, September 3. The social media platform has confirmed the hack, acknowledging the incident before stating that Twitter has taken steps to secure the compromised account. Twitter further said that it is “actively investigating” the issue, and claimed that it does not have knowledge of other similar accounts being attacked. According to a report, the perpetrators behind the breach was a hacker group named ‘John Wick’, who seemingly claimed that it did not have any particular intention with the hack – apart from clearing their own name from an alleged Paytm Mall hack from earlier this week.\r\n\r\nThe report by The Next Web states that the hackers also alleged that PM Modi’s own website, narendramodi.in, is riddled with bugs, and by hacking the website’s Twitter account, the group wanted to bring this to the notice of the site’s administrators. Reports also state that the hackers also posted tweets from the account asking for donations to a Bitcoin wallet, stating that the same will be contributed towards “PM relief fund for Covid-19”, or the PM-CARES that Narendra Modi has run during the pandemic. The tweet has since been deleted, and reports suggest that the mentioned Bitcoin account was not linked in any way to a relief fund. The hackers’ seemingly innocuous claims hence do not match with their actions.', '2020-09-03 13:20:19', 'Roushan Suman', 'bp7.webp'),
(2, 'Realme 7, Realme 7 Pro Launched in India: Price, Specifications and More', 'bp2.webp', 'The new Realme 7 series has officially launched in India that includes two new smartphones, the Realme 7 and the Realme 7 Pro. Both the new handsets are an upgrade for the Realme 6 series and feature a hole-punch display design with a quad-camera setup at the back. With the two new smartphones, Realme is competing with Xiaomi\'s Redmi Note 9 Pro series which offers almost identical hardware at a similar price point. The Realme 7 comes at a starting price of Rs 14,999 while the Realme 7 Pro starts at Rs 19,999. Notably, these smartphones pass the TUV Rheinland Smartphone Reliability Verification for a comfortable viewing experience by covering 23 major and 72 minor tests.\r\n', '2020-09-03 12:48:57', 'Shailabh Suman', 'bp2.webp'),
(3, 'Facebook To Halt New Political Ads Just Before U.S. Election', 'bp3.webp', 'The world’s biggest social network also said it was creating a label for posts by candidates or campaigns that try to claim victory before the election results are official, and widening the criteria for content to be removed as voter suppression.\r\n\r\nChief Executive Mark Zuckerberg wrote in a Facebook post announcing the changes that he was concerned about the unique challenges voters would face due to the coronavirus pandemic, which has prompted a surge in voting by mail.\r\n\r\n“I’m also worried that with our nation so divided and election results potentially taking days or even weeks to be finalized, there could be an increased risk of civil unrest across the country,” he said.\r\n\r\nZuckerberg has previously defended his decision to allow for a freewheeling political conversation on Facebook, including through paid ads, which the company exempts from its fact-checking program with external partners, including Reuters.\r\n\r\nHe said in his post he continued to believe that the “best antidote to bad speech is more speech,” but acknowledged that in the final days of an election, “there may not be enough time to contest new claims”.', '2020-09-03 13:00:09', 'Roushan Suman', 'bp3.webp'),
(4, 'PUBG Mobile Banned: Is Call of Duty Mobile Your Best Bet', 'bp4.webp', 'PUBG Mobile is facing a nationwide ban after it was listed as one of 118 Chinese apps in order by the Ministry of Electronics and Information Technology yesterday. Being one of the most popular mobile games in the country, the decision taken by the government to ban the game on the grounds of national security and integrity has led to an uproar among fans as well as professional and semi-professional players. Notably, the game has received criticism in the past for being a negative influence on the minds of youngsters.\r\n\r\nOne of the biggest potential gainers due to the ban could be Call of Duty Mobile. While the mobile adaptation of the popular PC/console game doesn’t have enough users in the country, it is considered to be a bigger name in the industry. While COD Mobile attempts to bring all the action of the original series, it also includes a battle royale mode of 100 players. There are also multiple other permanent and limited period game modes like Prop Hunt, Rapid Fire, Sticks, and Stones 2v2, Capture the Flag, One Shot One Kill, Snipers Only, and Gun Game, among others.', '2020-09-03 13:01:29', 'Roushan Suman', 'bp4.webp'),
(5, 'India Has Now Banned 224 Chinese Apps In Three Crackdowns As Attention Is On Aatmanirbhar Bharat', 'bp5.webp', 'This comes after the Government of India banned 59 apps on June 29 and followed that up with a second crackdown almost a month later by banning 47 more apps that cloned the apps previously restricted in India. This has been done deriving powers under the section 69A of the Information Technology Act read with the relevant provisions of the Information Technology (Procedure and Safeguards for Blocking of Access of Information by Public) Rules 2009 citing the concerns about the security, integrity and defence of India. Previously as well, popular apps that were banned included TikTok, Shareit, WeChat, Helo, Likee, UC News, Bigo Live, UC Browser, ES File Explorer and Mi Community. The government says these apps \"are engaged in activities which is prejudicial to sovereignty and integrity of India, defence of India, security of state and public order.\"', '2020-09-03 13:03:58', 'Shailabh Suman', 'bp5.webp'),
(6, 'Brazil Announces Equal Pay for Women\'s and Men\'s Football Teams', 'bp6.webp', 'It means Brazil\'s little known female players such as Marta, Formiga and Leticia Santos will receive the same fees and allowances as global superstars such as Neymar, Gabriel Jesus and Roberto Firmino.\r\n\r\nAustralia, Norway and New Zealand are amongst the nations to previously decide to pay their men and women internationals the same amount.\r\n\r\nIn March 2019, the US women\'s team, the current world champions, sued their federation alledging discrimination over pay and conditions.\r\n\r\nA judge dismissed their case in May this year but the team appealed.', '2020-09-03 13:05:45', 'Roushan Suman', 'bp6.webp'),
(8, 'Oppo Enco W51 True Wireless Earphones With Active Noise Cancellation Launched in India, Priced at Rs. 4,999', 'bp8.webp', 'Oppo Enco W51 true wireless stereo (TWS) earphones with active noise cancellation and wireless charging have been launched in India, priced at Rs. 4,999. The latest offering in Oppo\'s growing range of audio products and smart accessories, the Enco W51 were launched yesterday alongside the Oppo F17 and Oppo F17 Pro smartphones and will be available for sale soon. At this price, the Oppo Enco W51 is among the most affordable TWS earphones with premium features such as active noise cancellation in India.\r\n\r\nOppo Enco W51 price in India\r\nOppo Enco W51 are priced at Rs. 4,999 in India. These will be offered in two colours options - white and blue. No availability details have been announced yet, although the earphones are expected to be up for purchase soon.\r\n\r\nAlthough there are plenty of TWS earphones available at under Rs. 5,000 in India, the Oppo Enco W51 go a bit further by offering active noise cancellation and wireless charging. Both are typically premium features seen on TWS earphones priced at over Rs. 10,000. Oppo is bringing these features to the affordable space is an interesting move that could see other manufacturers also try to offer more in their upcoming products.', '2020-09-03 13:58:46', 'Shailabh Suman', 'bp8.webp'),
(9, 'Poco M2 set to launch in India on September 8 via Flipkart', 'bp9.jpg', 'After the launch of Poco M2 Pro, Xiaomi spin-off Poco is all set to launch the vanilla variant of the device in India called the Poco M2. The launch is confirmed to take place on September 8 at 12 pm via Flipkart.com. This will be an online-only event that will be live-streamed on the company\'s social media channels. \r\n\r\nPoco India took to Twitter to announce the launch of Poco M2 in the country. The tweet reads, \"It\'s time to change all your WTF moments to #PowerFTW moments. Get ready, the #POCOM2 is arriving on 08th September at 12 noon on Flipkart.\"\r\n\r\nThe company hasn\'t revealed any details about the device yet, but it is expected to drop more teasers in the coming days as we approach the launch date.', '2020-09-03 13:58:46', 'Roushan Suman', 'bp9.jpg'),
(10, 'Facebook Messenger Will Limit Forwarding Messages to Only Five People or Groups, Like WhatsApp', 'bp10.webp', 'Facebook Messenger has added a forwarding limit to let users forward messages only to five people or groups at a time. The new development is aimed to reduce the spread of viral misinformation and curb the circulation of fake news through the messaging platform. In 2018, Facebook brought a similar forwarding limit to WhatsApp in India, expanded to global markets in January last year. Meanwhile, in April, WhatsApp narrowed down the limit of frequently forwarded messages to one chat at a time. The Messenger app also recently added new privacy features, including the ability to lock the app on iOS devices.\r\n\r\nWith the addition of the forwarding limit to Messenger, you won\'t be able to forward any particular message to more than five people or groups simultaneously. If you try to add any new users to your forwarding list, the app will show you a notification saying, “forwarding limit reached.”\r\n\r\n“Limiting forwarding is an effective way to slow the spread of viral misinformation and harmful content that has the potential to cause real world harm,” said Jay Sullivan, Director of Product Management, Messenger Privacy and Safety, in a blog post on Thursday.', '2020-09-03 13:58:46', 'Anonymus', 'bp10.webp'),
(11, 'Microsoft is revamping Windows 10’s touch keyboard with better voice typing, GIFs, and emojis', 'bp11.jpg', 'Microsoft is rolling out a new touch keyboard design for some Windows Insiders in the latest update. The improved design offers a fresh aesthetic and brings a bunch of small tweaks, including updated key sizes and layouts for better typing comfort and accuracy.\r\n\r\n\r\nThe new design also includes refinements like new keypress animations and sounds, optimization for Child keys for quicker entry, a new button to undock the keyboard, improvements for all entries in the settings menu, emoji, and GIF search support, and a new voice typing button. The touch keyboard can now also be invoked on any PC from the touch keyboard button on the taskbar. However, users may need to enable the button from the settings first.', '2020-09-03 13:58:46', 'Anonymus', 'bp11.jpg'),
(12, 'BL’s latest affordable Bluetooth speakers are waterproof and charge via USB-C', 'bp12.webp', 'JBL has announced new Clip 4 and Go 3 miniature Bluetooth speakers. Both have gotten a visual makeover from their predecessors, with a streamlined design and a few new colors available. The Go 3 will launch first in October for $39.95. The Clip 4 will follow in December for $69.95.\r\n\r\nIn terms of improvements, both speakers support Bluetooth 5.1 and have IP67 water and dustproofing. And instead of charging via Micro USB, which can be inconvenient, they feature a USB-C port. JBL claims the Go 3 will provide up to five hours of sound before needing to be recharged, while the Clip 4 can apparently provide 10 hours. Neither of those figures strays from the performance claims of the previous iterations.', '2020-09-03 13:58:46', 'Shailabh Suman', 'bp12.webp');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
